.github/workflows/tests.yml
README.md

Create a CI GitHub action with a `rule_linter` job similar to the one in [capa](https://github.com/fireeye/capa/pull/166).

Run rules linter in master and PRs 

---

nursery/acquire-debug-privileges.yml
nursery/import-public-key.yml
nursery/terminate-process-by-name.yml

unfortunately, haven't found a public sample of the ransomware yet

add a couple new rules derived from Cl0p ransomware

---

nursery/hash-data-using-sha1-via-x86-extensions.yml
nursery/hash-data-using-sha256-via-x86-extensions.yml

Added in support for the SHA family of instructions shown here -> https://software.intel.com/content/www/us/en/develop/articles/intel-sha-extensions.html
These are put into the nursery as I could not find a sample in my corpus that matched.

SHA1 &SHA256 via processor extensions

---

host-interaction/gui/window/hide/hide-graphical-window.yml
nursery/get-file-version-info.yml
nursery/get-socket-information.yml
nursery/set-graphical-window-text.yml

Misc new rules and rule updates 🚀

adding misc new rules and rule updates

---

nursery/Update bypass-uac-via-appinfo-alpc.yml

Create Update bypass-uac-via-appinfo-alpc.yml

---

data-manipulation/encryption/rc4/encrypt-data-using-rc4-ksa.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-prga.yml

closes #91
having issues adding the new test binary, but should get that in eventually

improve RC4 rules

---

data-manipulation/hashing/murmur/hash-data-using-murmur3.yml

Include more ways to detect MurmurHash3 algorithm.
For reference check the algorithm at:
https://en.wikipedia.org/wiki/MurmurHash

Improve hash-data-using-murmur3 rule

---

anti-analysis/anti-av/check-for-sandbox-and-av-modules.yml
data-manipulation/compression/decompress-data-via-iencodingfilterfactory.yml
doc/format.md
linking/runtime-linking/access-peb-ldr_data.yml

fixed description key, and added x32 and x64 flavours

---

data-manipulation/encryption/rsa/reference-public-rsa-key.yml
host-interaction/mutex/check-mutex-and-exit.yml
linking/runtime-linking/link-many-functions-at-runtime.yml
nursery/hash-data-using-fnv.yml

New rules from recent samples, including a ransomware (added in https://github.com/fireeye/capa-testfiles/pull/16)

add new rules

---

data-manipulation/encryption/camellia/encrypt-data-using-camellia.yml

Per https://github.com/fireeye/capa-rules/pull/106#issuecomment-683137923

Update example offset in encrypt-data-using-camellia

---

data-manipulation/encryption/sosemanuk/encrypt-data-using-sosemanuk.yml

Fix #117 - Add encrypt-data-using-sosemanuk

---

anti-analysis/anti-debugging/debugger-detection/check-for-trap-flag-exception.yml
anti-analysis/anti-vm/vm-detection/check-for-sandbox-username.yml
data-manipulation/compression/decompress-data-using-quicklz.yml
data-manipulation/encryption/des/encrypt-data-using-des.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-ksa.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-prga.yml
data-manipulation/hashing/murmur/hash-data-using-murmur3.yml
data-manipulation/hashing/tiger/hash-data-using-tiger.yml
doc/format.md
lib/validate-credit-card-number-using-luhn-algorithm-with-lookup-table.yml
lib/validate-credit-card-number-using-luhn-algorithm-with-no-lookup-table.yml

discussed in https://github.com/fireeye/capa/issues/312

comment out description blocks for statements

---

data-manipulation/encryption/hc-128/encrypt-data-using-hc-128.yml
nursery/encrypt-data-using-hc-128.yml

Fix #132 - Add encrypt-data-using-hc-128

Fix #132 - Add encrypt-data-using-hc-128

---

doc/format.md

accounts for changes in https://github.com/fireeye/capa/pull/327

update documentation on descriptions

---

anti-analysis/anti-debugging/debugger-detection/check-for-trap-flag-exception.yml
data-manipulation/compression/decompress-data-using-quicklz.yml
data-manipulation/encryption/des/encrypt-data-using-des.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-ksa.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-prga.yml
data-manipulation/hashing/murmur/hash-data-using-murmur3.yml
data-manipulation/hashing/tiger/hash-data-using-tiger.yml
lib/validate-credit-card-number-using-luhn-algorithm-with-lookup-table.yml
lib/validate-credit-card-number-using-luhn-algorithm-with-no-lookup-table.yml
nursery/empty-recycle-bin-quietly.yml

I've enabled the descriptions again and reordered in most instances. Would appreciate a quick check that I didn't mess up indentations.

use new description syntax

---

anti-analysis/packer/nspack/packed-with-nspack.yml
anti-analysis/packer/pebundle/packed-with-pebundle.yml
anti-analysis/packer/pelocknt/packed-with-pelocknt.yml

A continuation to https://github.com/fireeye/capa-rules/pull/149

More packer rules based on section names

---

anti-analysis/anti-forensic/clear-logs/clear-the-windows-event-log.yml
anti-analysis/anti-forensic/crash-the-windows-event-logging-service.yml

adding new rules inspired by https://github.com/limbenjamin/LogServiceCrash
closes #148

adding new Windows event logging rules

---

host-interaction/console/manipulate-console.yml
nursery/hook-routines-via-microsoft-detours.yml

example file added in https://github.com/fireeye/capa-testfiles/pull/28

add a couple new rules

---

anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml
executable/pe/64-bit-execution-via-heavens-gate.yml

Proposed rule for #160 
See https://github.com/fireeye/capa-testfiles/pull/35 for test file

[WIP] Fix #160 - 64-bit-execution-via-heavens-gate

---

nursery/encrypt-or-decrypt-data-via-bcrypt.yml
nursery/hash-data-via-bcrypt.yml

adding new BCrypt rules for encrypt/decrypt/hash.

new BCrypt rules

---

data-manipulation/checksum/luhn/validate-payment-card-number-using-luhn-algorithm.yml
lib/validate-payment-card-number-using-luhn-algorithm-with-lookup-table.yml
lib/validate-payment-card-number-using-luhn-algorithm-with-no-lookup-table.yml

Adjusting rule names and descriptions.
https://github.com/fireeye/capa-rules/issues/178

Fix for #178

---

anti-analysis/anti-disasm/contain-anti-disasm-techniques.yml
anti-analysis/packer/generic/packed-with-generic-packer.yml
lib/contain-pusha-popa-sequence.yml

Example from a5c70086b3bc4fe64f4e7a0aa452e620
```asm
.text:35007200 55                                push    ebp
.text:35007201 8B EC                             mov     ebp, esp
.text:35007203 81 EC 38 02 00 00                 sub     esp, 238h
.text:35007209 53                                push    ebx
.text:3500720A 56                                push    esi
.text:3500720B 57                                push    edi
.text:3500720C 60                                pusha
.text:3500720D 83 EC 04                          sub     esp, 4
.text:35007210 B0 01                             mov     al, 1
.text:35007212 FE C0                             inc     al
.text:35007214 75 06                             jnz     short loc_3500721C
.text:35007216 81 C4 90 00 00 00 …
```

find pusha popa sequences

---

compiler/go/compiled-with-go.yml

Graduating `compiled-with-go` now that a sample is in `capa-testfiles`

Graduate compiled-with-go.yml

---

collection/network/get-mac-address.yml

Graduating get-mac-address, relevant code appears in Al Khaser
https://github.com/LordNoteworthy/al-khaser/blob/9fbe13a0e5639d06b3cd3ab5ab96cd82445f7691/al-khaser/Shared/Utils.cpp#L86

Graduate get-mac-address.yml

---

anti-analysis/anti-vm/vm-detection/execute-anti-vm-instructions.yml

disable cpuid feature for now

---

doc/format.md

document example syntax

---

.github/workflows/tests.yml

Gets modified files and lints them thoroughly. All rules are also linted regularly before that.

lint modified rules thoroughly

---

.github/workflows/tests.yml

The renamed sample in #243 slipped through.

thoroughly lint renamed files also

---

communication/socket/tcp/connect-tcp-socket.yml

connect-tcp-socket: add ConnectEx via WSAID_CONNECTEX

---

anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings.yml
nursery/reference-dns-over-https-endpoints.yml

rule fixes

---

anti-analysis/anti-vm/vm-detection/check-for-unmoving-mouse-cursor.yml

Fixed example

---

host-interaction/session/get-session-integrity-level.yml

```
python scripts\lint.py rules\host-interaction\session\get-session-integrity-level.yml --thorough
INFO:capa.lint:successfully loaded 1 rules
INFO:capa.lint:collecting potentially referenced samples
INFO:capa.lint:no suggestions, nice!
```

fixes #248

---

nursery/compiled-with-nim.yml

adding compiled-with-nim.yml

---

.github/workflows/tests.yml

continue on get-changed-files Action error

---

compiler/vb/compiled-from-visual-basic.yml

add compiled-from-visual-basic.yml

---

compiler/exe4j/compiled-with-exe4j.yml

https://github.com/fireeye/capa-rules/issues/261
Closes #261

compiled-with-exe4j.yml

---

executable/installer/iexpress/packaged-as-an-iexpress-self-extracting-archive.yml

Add packaged-as-an-iexpress-self-extracting-archive

---

.github/workflows/sync.yml
.github/workflows/tests.yml

ci: pin OS versions

---

data-manipulation/compression/decompress-data-using-aplib.yml
data-manipulation/encryption/elliptic-curve/encrypt-data-using-curve25519.yml
linking/runtime-linking/resolve-function-by-fin8-fasthash.yml

this includes and supersedes #310

add rules from fboldewin

---

anti-analysis/packer/confuser/packed-with-confuser.yml
compiler/pyarmor/compiled-with-pyarmor.yml
data-manipulation/encoding/base64/encode-data-using-base64.yml
data-manipulation/encoding/base64/reference-base64-string.yml
data-manipulation/encoding/xor/encode-data-using-xor.yml
host-interaction/file-system/write/write-file.yml
host-interaction/hardware/cdrom/manipulate-cd-rom-drive.yml
host-interaction/registry/create-registry-key-via-offline-registry-library.yml
host-interaction/registry/delete/delete-registry-key.yml
host-interaction/registry/delete/delete-registry-value.yml
host-interaction/registry/set-registry-key-via-offline-registry-library.yml
load-code/pe/inject-dll-reflectively.yml
nursery/check-for-process-debug-object.yml
nursery/check-processdebugflags.yml
nursery/check-processdebugport.yml
nursery/check-systemkerneldebuggerinformation.yml
nursery/check-thread-yield-allowed.yml
nursery/decode-data-using-base64-via-winapi.yml
nursery/decrypt-data-via-sspi.yml
nursery/delete-registry-key-via-offline-registry-library.yml
nursery/encode-data-using-base64-via-winapi.yml
nursery/enumerate-network-shares.yml
nursery/get-user-security-identifier.yml
nursery/reference-processor-manufacturer-constants.yml
nursery/reference-the-vmware-io-port.yml

thanks to Regina Elwell @ FireEye and @evandrix
closes #316

update ATT&CK and MBC mappings

---

anti-analysis/anti-vm/vm-detection/execute-anti-vm-instructions.yml

Fix execute anti-VM instructions

---

host-interaction/network/domain/get-domain-information.yml
host-interaction/process/terminate/terminate-process.yml
host-interaction/session/get-logon-sessions.yml

Let me know if you'd like me to open tickets corresponding to these two new rules.
Test sample: https://github.com/fireeye/capa-testfiles/pull/86
Thanks!

Add rules from Egregor ransomware DLL

---

host-interaction/file-system/bypass-mark-of-the-web.yml

add bypass mark of the web

---

collection/acquire-credentials-from-windows-credential-manager.yml
collection/get-geographical-location.yml
collection/network/capture-public-ip.yml
host-interaction/process/create/create-process.yml
nursery/persist-via-active-setup-registry-key.yml
persistence/registry/persist-via-active-setup-registry-key.yml

Collecting my updates here. Will ask for a review once I've gathered a few.
- https://attack.mitre.org/techniques/T1547/014/ - closes #343
- https://attack.mitre.org/techniques/T1555/004 - closes #349
- https://attack.mitre.org/techniques/T1614 - closes #361

ATT&CK v9 updates

---

host-interaction/bootloader/manipulate-boot-configuration.yml
host-interaction/driver/disable-driver-code-integrity.yml

address optional blocks

---

nursery/bypass-uac-via-icmluautil.yml

ICMLuaUtil: fix logic, add description

---

nursery/execute-syscall-instruction.yml

per @kulinacs suggestion in https://github.com/fireeye/capa/issues/233

add `execute syscall instruction`

---

collection/file-managers/gather-leapftp-information.yml
data-manipulation/hashing/tiger/hash-data-using-tiger.yml
host-interaction/os/version/check-os-version.yml
nursery/capture-screenshot-in-go.yml
nursery/linked-against-go-process-enumeration-library.yml
nursery/linked-against-go-wmi-library.yml

see #382 and https://github.com/fireeye/capa/pull/563

remove single child statements

---

doc/format.md

document `function-name` feature added in https://github.com/fireeye/capa/pull/568

format: document function-name feature

---

communication/http/client/create-bits-job.yml
compiler/nim/compiled-with-nim.yml
data-manipulation/encoding/base64/decode-data-using-base64-via-winapi.yml
data-manipulation/encoding/base64/encode-data-using-base64-via-winapi.yml
data-manipulation/hmac/authenticate-hmac.yml
host-interaction/file-system/meta/get-file-size.yml
host-interaction/file-system/meta/get-file-version-info.yml
host-interaction/gui/console/set-console-window-title.yml
host-interaction/process/modify/acquire-debug-privileges.yml
host-interaction/wmi/connect-to-wmi-namespace-via-wbemlocator.yml
nursery/compiled-from-epl.yml
nursery/encode-data-using-base64-via-winapi.yml

10 graduations, one fix
should be a quick review

2021 06 04 graduation

---

anti-analysis/anti-forensic/impersonate-file-version-information.yml

Test file in https://github.com/fireeye/capa-testfiles/pull/99

Add impersonate-file-version-information

---

internal/limitation/file/internal-visual-basic-file-limitation.yml

closes https://github.com/fireeye/capa/issues/587

add VB limitation

---

host-interaction/network/traffic/filter/register-network-filter-via-wfp-api.yml

register-network-filter-via-wfp-api: fix ATT&CK mapping

---

nursery/list-drag-and-drop-files.yml
nursery/monitor-clipboard-content.yml
nursery/monitor-local-ipv4-address-changes.yml

closes #432 
closes #431 
closes #430

adding misc. rules to nursery

---

nursery/resize-volume-shadow-copy-storage.yml

adding resize-volume-shadow-copy-storage.yml

---

nursery/delete-user-account.yml
nursery/list-domain-servers.yml
nursery/list-user-account-groups.yml
nursery/list-user-accounts-for-group.yml

update ATT&CK mappings

---

anti-analysis/anti-forensic/self-deletion/self-delete.yml
anti-analysis/packer/pecompact/packed-with-pecompact.yml
host-interaction/driver/create-device-object.yml
host-interaction/file-system/read/read-file-via-mapping.yml
host-interaction/gui/window/get-text/get-graphical-window-text.yml
host-interaction/mutex/check-mutex-and-exit.yml
host-interaction/process/create/execute-command.yml
host-interaction/process/list/enumerate-processes.yml
host-interaction/process/modules/list/enumerate-process-modules.yml
host-interaction/thread/list/enumerate-threads.yml
load-code/pe/parse-pe-header.yml
load-code/shellcode/spawn-thread-to-rwx-shellcode.yml

adding rules based on more PMA labs

---

data-manipulation/encryption/create-new-key-via-cryptacquirecontext.yml

Add rule for CryptAcquireContext CRYPT_NEWKEYSET

---

doc/format.md

ref: https://github.com/fireeye/capa/pull/739

format: document substring features

---

communication/http/client/check-http-status-code.yml
nursery/linked-against-cpp-http-library.yml
nursery/linked-against-cpp-json-library.yml
nursery/linked-against-cpp-regex-library.yml

some additions and a fix for a linux FP
closes #418

rule additions and updates

---

anti-analysis/packer/upx/packed-with-upx.yml

supports https://github.com/fireeye/capa/pull/770

update UPX for ELF

---

anti-analysis/anti-forensic/patch-process-command-line.yml
communication/dns/reference-dns-over-https-endpoints.yml
communication/http/client/create-bits-job.yml
data-manipulation/compression/decompress-data-using-aplib.yml
data-manipulation/hashing/md5/hash-data-with-md5.yml
data-manipulation/hmac/authenticate-hmac.yml
host-interaction/bootloader/manipulate-boot-configuration.yml
host-interaction/driver/disable-driver-code-integrity.yml
host-interaction/environment-variable/get-comspec-environment-variable.yml
host-interaction/file-system/move/move-file.yml
host-interaction/file-system/read/read-file-via-mapping.yml
host-interaction/filter/register-minifilter-driver.yml
host-interaction/filter/start-minifilter-driver.yml
host-interaction/gui/console/set-console-window-title.yml
host-interaction/process/dump/create-process-memory-minidump.yml
host-interaction/thread/list/enumerate-threads.yml
lib/open-process.yml
lib/open-thread.yml
linking/runtime-linking/resolve-function-by-fin8-fasthash.yml
load-code/pe/enumerate-pe-sections.yml
load-code/pe/inspect-section-memory-permissions.yml
load-code/pe/rebuild-import-table.yml

Added Malware Behavior Catalog (MBC) mappings for capa 2.0 rules

Update Mappings for MBC (part 6)

---

nursery/capture-webcam-video.yml

closes #286 
Hello guys,
unfortunately I couldn't find a sample that met the logic proposed in the ISSUE, for this reason I submitted it as "nursery".

 capture-webcam-video #286

---

load-code/shellcode/execute-shellcode-via-windows-fibers.yml

Adding execute-shellcode-via-windows-fibers.yml

---

load-code/shellcode/execute-shellcode-via-enumuilanguages.yml

New rule that detects potential execution of shellcode via callback function in `EnumUILanguages`

Adding execute-shellcode-via-enumuilanguages.yml

---

anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings-targeting-vmware.yml

updating reference-anti-vm-strings-targeting-vmware.yml

---

load-code/shellcode/execute-shellcode-via-createthreadpoolwait.yml

New rule that detects potential execution of shellcode via callback function in CreateThreadpoolWait

Adding execute-shellcode-via-createthreadpoolwait.yml

---

host-interaction/process/inject/inject-shellcode-using-a-file-mapping-object.yml
host-interaction/process/inject/inject-shellcode-using-mapping-injection.yml

New rule that detects process injection using the Mapping Injection technique.

Adding inject-shellcode-using-mapping-injection.yml

---

load-code/shellcode/execute-shellcode-via-copyfile2.yml

New rule that detects shellcode execution via callback function in CopyFile2

Adding execute-shellcode-via-copyfile2.yml

---

anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml
doc/format.md

see https://github.com/mandiant/capa/pull/899 and https://github.com/mandiant/capa/pull/902

call $+5 update rule and doc

---

data-manipulation/encryption/aes/manually-build-aes-constants.yml

Issue #539: Sample manually build AES/Rijndael boxes

---

anti-analysis/packer/huan/packed-with-huan.yml

New rule that identifies files "packed" (encrypted) with Huan (https://github.com/frkngksl/Huan).

Adding packed-with-huan.yml

---

nursery/get-os-information-via-kuser_shared_data.yml

get OS information via KUSER_SHARED_DATA

---

anti-analysis/obfuscation/obfuscated-with-callobfuscator.yml
data-manipulation/encryption/aes/manually-build-aes-constants.yml

Update Mappings for MBC (part 8)

---

communication/http/client/create-bits-job.yml
nursery/resolve-function-by-hash.yml
targeting/automated-teller-machine/diebold-nixdorf/reference-diebold-atm-routines.yml

ref: https://github.com/mandiant/capa/issues/800

*: fix blog links

---

.github/workflows/tests.yml

Lint all rules thoroughly when this is set:

ci: lint thorough on PR text

---

host-interaction/cli/accept-command-line-arguments.yml
host-interaction/network/interface/get-networking-interfaces.yml
host-interaction/session/get-session-user-name.yml

The following rules are updated with dotnet capabilities:
- `accept command line arguments`
- `get networking interfaces`
- `get session user name`

Add dotnet rules

---

anti-analysis/packer/themida/packed-with-themida.yml
host-interaction/hardware/storage/enumerate-disk-properties.yml
host-interaction/process/create/create-process-on-windows.yml
nursery/display-service-notification-message-box.yml
runtime/dotnet/compiled-to-the-dotnet-platform.yml

fix: rule logic

---

anti-analysis/obfuscation/obfuscated-with-babel-obfuscator.yml
anti-analysis/obfuscation/obfuscated-with-deepsea-obfuscator.yml
anti-analysis/obfuscation/obfuscated-with-dotfuscator.yml
anti-analysis/obfuscation/obfuscated-with-smartassembly.yml
anti-analysis/obfuscation/obfuscated-with-spicesdotnet-obfuscator.yml
anti-analysis/obfuscation/obfuscated-with-yano.yml

Adding multiple rules for common .Net obfuscators.
obfuscated-with-smartassembly.yml fixes https://github.com/mandiant/capa-rules/issues/570

Adding .Net obfuscation rules.

---

communication/http/server/start-http-server.yml

Updated start-http-server.yml with .Net API

---

anti-analysis/obfuscation/obfuscated-with-vs-obfuscation.yml

Adding obfuscated-with-vs-obfuscation.yml

---

data-manipulation/checksum/crc32/hash-data-with-crc32.yml

Improve CRC32

---

host-interaction/file-system/files/list/enumerate-files-on-linux.yml
host-interaction/file-system/files/list/enumerate-files-on-windows.yml
host-interaction/file-system/files/list/enumerate-files-recursively.yml
load-code/powershell/run-powershell-expression.yml

Update Mappings for MBC (part 9)

---

.github/workflows/tests.yml

See discussion at https://github.com/mandiant/capa-rules/issues/556#issuecomment-1242375052

ci: test latest release on master branch only

---

nursery/check-for-vm-using-instruction-vpcext.yml

Dear Colleagues,
please have a look at my capa rule. I would be pleased to get additional feedback.
Kind regards,
Richard

added anti-analysis - anti-vm - vpcext

---

host-interaction/wmi/connect-to-wmi-namespace-via-wbemlocator.yml
nursery/implement-com-dll.yml
nursery/linked-against-libsodium.yml

Rules 2023 01

---

compiler/nuitka/compiled-with-nuitka.yml

add compiled-with-nuitka

---

nursery/authenticate-data-with-md5-mac.yml

ref #632
wasnt able to find an x86 code example on VT

add authenticate data with md5 mac

---

data-manipulation/hashing/sha1/hash-data-using-sha1.yml

more SHA1 constants

---

data-manipulation/hashing/sha224/hash-data-using-sha224.yml
data-manipulation/hashing/sha256/hash-data-using-sha256.yml
data-manipulation/hashing/sha384/hash-data-using-sha384.yml
data-manipulation/hashing/sha512/hash-data-using-sha512.yml

ref #632
https://github.com/mandiant/capa-testfiles/pull/151

sha* rules and updates

---

.github/workflows/tests.yml

add weekly scheduled run of lint --thorough

---

data-manipulation/encryption/rc6/encrypt-data-using-rc6.yml

rc5/6: more constants

---

host-interaction/os/version/check-os-version.yml
lib/get-os-version.yml

add library rule and new api

---

anti-analysis/obfuscation/string/stackstring/contain-obfuscated-stackstrings.yml

add stack strings MBC

---

nursery/reference-base58-string.yml

add base58

---

communication/mailslot/create-mailslot.yml

closes #620 
https://github.com/mandiant/capa-testfiles/pull/152
cc: @captainGeech42

add create-mailslot

---

compiler/nuitka/compiled-with-nuitka.yml
data-manipulation/encryption/rc4/encrypt-data-using-rc4-ksa.yml
executable/resource/access-dotnet-resource.yml
linking/static/linked-against-cpp-standard-library.yml

closes #640
closes #541
closes #520

Rules for the week

---

data-manipulation/compression/compress-data-using-lzo.yml
data-manipulation/compression/decompress-data-using-lzo.yml

addressing feedback added to #623
supersedes #623

LZO compression / decompression rules continued

---

communication/socket/tcp/create-tcp-socket-via-raw-afd-driver.yml

closes #537
https://github.com/mandiant/capa-testfiles/pull/153

add create tcp socket via raw AFD driver

---

host-interaction/process/access-section-object.yml
host-interaction/process/inject/inject-apc.yml
host-interaction/process/map-section-object.yml
lib/create-or-open-section-object.yml

add section access/map rules

---

anti-analysis/anti-forensic/hide-shadow-copy.yml
anti-analysis/anti-forensic/hide-volume-shadow-copy.yml

This rules passes thorough linting and closes #554

Add hide shadow copy (#554)

---

data-manipulation/prng/generate-random-numbers-via-rtlgenrandom.yml

generate random numbers via RtlGenRandom

---

compiler/rust/compiled-with-rust.yml

add more common rust-related strings

rust: add more strings

---

executable/installer/dotnet/packaged-as-single-file-dotnet-application.yml
nursery/packaged-as-single-file-dotnet-application.yml

adding "packaged as single-file .NET application"

---

communication/http/get-http-content-length.yml

add get http content length

---

communication/socket/receive/receive-data-on-socket.yml

https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-7.0#methods

update recieve-data-on-socket for .NET

---

doc/format.md

closes #711 
depends on https://github.com/mandiant/capa/pull/1324

update doc for OS_ANY

---

communication/dns/resolve-dns.yml
nursery/reference-cryptocurrency-strings.yml

closes #683
closes #709
At least two minor updates this week 😄

DNS and crypto rule tweaks

---

load-code/pe/enumerate-pe-sections.yml
load-code/pe/parse-pe-header.yml

specify offset operand to reduce FPs

---

host-interaction/file-system/reference-absolute-stream-path-on-windows.yml

closes #717
@bkojusner please review

absolute stream path: fix slow regex

---

doc/format.md

Updates to format readme

---

nursery/check-for-minimum-number-of-windows-on-screen.yml

No example due to API Hashing obfuscating call in all samples I found.

Adding new anti-vm technique from guloader - minimum windows on screen check

---

anti-analysis/anti-vm/vm-detection/check-for-microsoft-office-emulation.yml
anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-device.yml
host-interaction/file-system/read/read-file-on-windows.yml
host-interaction/file-system/write/write-file-on-windows.yml
impact/wipe-disk/wipe-mbr/overwrite-master-boot-record-mbr.yml

match on create or open file library rule

---

nursery/compiled-with-exescript.yml

Add rule compiled-with-exescript.yml
closes issue #737

Add rule compiled-with-exescript.yml

---

nursery/check-for-sandbox-via-mac-address-ouis-in-dotnet.yml

Add rule check-for-sandbox-via-mac-address-ouis-in-dotnet

---

host-interaction/hardware/enumerate-devices-by-category.yml

add rule enumerate devices by category

---

host-interaction/file-system/copy/copy-file.yml
host-interaction/file-system/read/read-file-on-windows.yml
lib/create-or-open-file.yml

Add LZ* functions

---

communication/http/reference-http-user-agent-string.yml
communication/socket/create-raw-socket.yml
data-manipulation/compression/compress-data-via-zlib-inflate-or-deflate.yml
host-interaction/process/inject/inject-apc.yml
impact/wipe-disk/wipe-mbr/overwrite-master-boot-record-mbr.yml

Update Mappings for MBC (Part 11)

---

persistence/exchange/act-as-exchange-transport-agent.yml

Add act-as-exchange-transport-agent.yml

Add act-as-exchange-transport-agent.yml

---

host-interaction/file-system/create-virtual-file-system-in-dotnet.yml

Add create-virtual-file-system-in-dotnet.yml

Add create-virtual-file-system-in-dotnet.yml

---

communication/socket/create-vmci-socket.yml

Add create-vmci-socket.yml

---

persistence/office/act-as-excel-xll-add-in.yml
persistence/office/act-as-office-com-add-in.yml
persistence/office/act-as-word-wll-add-in.yml

Add Office Add-ins rules.

---

host-interaction/memory/create-new-application-domain-in-dotnet.yml

Add create-new-application-domain-in-dotnet.yml

Add create-new-application-domain-in-dotnet.yml

---

anti-analysis/anti-debugging/debugger-evasion/switch-active-desktop.yml
host-interaction/gui/switch-active-desktop.yml

Add switch-active-desktop.yml

---

collection/microphone/capture-microphone-audio.yml

add winmm wave functions

---

anti-analysis/anti-av/patch-event-tracing-for-windows-function.yml

Add patch-event-tracing-for-windows-function.yml

Add patch-event-tracing-for-windows-function.yml

---

persistence/create-shortcut-via-ishelllink.yml

Update metadata and promote create-shortcut-via-ishelllink.yml

Update metadata and promote create-shortcut-via-ishelllink.yml

---

host-interaction/bootloader/get-uefi-variable.yml
host-interaction/bootloader/set-uefi-variable.yml

Add get-uefi-variable.yml and set-uefi-variable.yml

Add get-uefi-variable.yml and set-uefi-variable.yml

---

nursery/deserialize-json-in-dotnet.yml
nursery/serialize-json-in-dotnet.yml

Update .NET JSON detections

---

host-interaction/process/inject/free-user-process-memory.yml

fix example function address

---

lib/allocate-memory.yml

Part of covering APIs mentioned in #88

add xxProtectVirtualMemory apis

---

collection/network/capture-packets-using-sharppcap.yml

Add capture-packets-using-sharppcap.yml

Add capture-packets-using-sharppcap.yml

---

doc/format.md

Documentation for COM feature addition in https://github.com/mandiant/capa/pull/1738
reference to https://github.com/mandiant/capa/issues/322

Documentation for COM feature addition

---

doc/format.md

Update doc apis no dlls

---

host-interaction/thread/tls/allocate-thread-local-storage.yml
host-interaction/thread/tls/set-thread-local-storage-value.yml

Update TLS namespaces

---

host-interaction/hardware/enumerate-devices-by-category.yml
host-interaction/wmi/connect-to-wmi-namespace-via-wbemlocator.yml

closes #853 
the other IDs/classes seem to be missing/unrelated

Use COM instead of bytes features

---

data-manipulation/compression/create-cabinet-on-windows.yml

Note: We have introduced edits to move Archive Collected Data [E1560] to the Collection Objective in MBC

Update Mappings for MBC (Q4 2023)

---

host-interaction/process/inject/process-ghostly-hollowing.yml

Ghostly Hollowing injection technique described here https://github.com/hasherezade/transacted_hollowing/tree/main#ghostly-hollowing

Ghostly Hollowing process injection rule

---

impact/wipe-disk/delete-drive-layout-via-ioctl.yml

closes #877
sample in https://github.com/mandiant/capa-testfiles/pull/226

add delete drive layout via ioctl

---

.github/workflows/sync.yml

Closes https://github.com/mandiant/capa-rules/issues/884

[CI] Correct token used to update badge

---

load-code/shellcode/execute-shellcode-via-windows-callback-function.yml

This PR adds more APIs related to shellcode execution via callbacks for the existing rule.

Add additional shellcode execution callback functions

---

load-code/shellcode/execute-shellcode-via-windows-callback-function.yml

Add EnumProps to callback shellcode execution rule

---

host-interaction/file-system/change-file-permission-on-linux.yml
host-interaction/process/create/create-process-on-linux.yml
nursery/change-memory-permission-on-linux.yml
nursery/check-file-permission-on-linux.yml
nursery/check-if-process-is-running-under-android-emulator-on-android.yml
nursery/map-or-unmap-memory-on-linux.yml

adding new and updating linux / android rules

---

persistence/act-as-share-provider-dll.yml
persistence/act-as-windbg-extension.yml

Add two new CAPA rules: act-as-share-provider-dll.yml and act-as-windbg-extension.yml

Add two new CAPA rules: act-as-share-provider-dll.yml and act-as-windbg-extension.yml

---

persistence/act-as-time-provider-dll.yml

Add new rule act-as-time-provider-dll.yml

Add new rule act-as-time-provider-dll.yml

---

host-interaction/gui/window/hide/hide-graphical-window-from-taskbar.yml

Add hide-graphical-window-from-taskbar.yml rule

Add hide-graphical-window-from-taskbar.yml rule

---

compiler/dart/compiled-with-dart.yml

Add rule compiled-with-dart.yml

Add rule compiled-with-dart.yml

---

communication/socket/attach-bpf-to-socket-on-linux.yml

Add new rule attach-bpf-to-socket-on-linux.yml

Add new rule attach-bpf-to-socket-on-linux.yml

---

nursery/decode-data-using-base64-via-vbmi-lookup-table.yml

remove example and move to nursery

---

host-interaction/hardware/firmware/get-system-firmware-table.yml

Move from nursery and update `get-system-firmware-table.yml`

Move from nursery and update get-system-firmware-table.yml

---

anti-analysis/packer/nmm-protect/packed-with-nmm-protect.yml

https://github.com/mandiant/capa-testfiles/pull/264

add packed-with-nmm-protect

---

anti-analysis/anti-vm/vm-detection/check-for-unmoving-mouse-cursor.yml

disable for dynamic scope

---

data-manipulation/encryption/create-new-key-via-cryptacquirecontext.yml

tighten scopes

---

nursery/hook-routines-via-microsoft-detours.yml

@williballenthin do you recall why this was commented out 4 years ago?
:rofl:

enable namespace

---

anti-analysis/anti-vm/vm-detection/check-for-sandbox-username-or-hostname.yml

Fixes https://github.com/mandiant/capa-rules/issues/974

https://github.com/mandiant/capa-rules/issues/974

---

host-interaction/registry/change-registry-key-timestamp.yml

closes #1000
https://github.com/mandiant/capa-testfiles/pull/275

add "change registry key timestamp"

---

host-interaction/process/list/enumerate-processes-on-remote-desktop-session-host.yml
nursery/impersonate-user.yml

Added detection for token impersonation via duplication of existing token.
Reference:
[getel-arch/Token-Impersonation](https://github.com/getel-arch/Token-Impersonation)

Improve Accuracy of Various Detections

---

host-interaction/gui/taskbar/find/find-taskbar.yml
host-interaction/gui/window/find/find-graphical-window.yml

reduce scopes to remove _find-taskbar_ fps

---

anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings-targeting-virtualbox.yml
anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings.yml
nursery/disable-device-guard-features-via-registry-on-windows.yml
nursery/disable-firewall-features-via-registry-on-windows.yml
nursery/disable-system-features-via-registry-on-windows.yml
nursery/disable-system-restore-features-via-registry-on-windows.yml
nursery/disable-windows-defender-features-via-registry-on-windows.yml
nursery/enumerate-device-drivers-on-windows.yml
nursery/persist-via-appcertdlls-registry-key.yml
nursery/persist-via-autodialdll-registry-key.yml
nursery/persist-via-bootverificationprogram-registry-key.yml
nursery/persist-via-lsa-registry-key.yml
nursery/persist-via-natural-language-registry-key.yml
nursery/persist-via-network-provider-registry-key.yml
nursery/persist-via-print-monitors-registry-key.yml
nursery/persist-via-print-processors-registry-key.yml
nursery/persist-via-rdp-startup-programs-registry-key.yml
nursery/persist-via-timeproviders-registry-key.yml
nursery/persist-via-ts-initialprogram-registry-key.yml
persistence/registry/run/persist-via-run-registry-key.yml
persistence/service/persist-via-windows-service.yml

add new rules to detect disabling system features via registry on Windows

---

linking/static/grpc/linked-against-grpc.yml

Add linking/static/grpc/linked-against-grpc.yml

Add linking/static/grpc/linked-against-grpc.yml

---

load-code/execute-jscript-via-vsaengine-in-dotnet.yml

Add rule execute-jscript-via-vsaengine-in-dotnet.yml

Add rule execute-jscript-via-vsaengine-in-dotnet.yml
