mandiant/capa-rules

.github/workflows/sync.yml
Seems like something's off here
Reverts fireeye/capa-rules#40
=> Revert "Improve capa checkout in sync workflow"

.github/workflows/sync.yml
[@williballenthin mentioned when this was introduced that it would be nice to not checkout the `tests/data` submodule (as it is big)](https://github.com/fireeye/capa-rules/pull/36#discussion_r454529546). I've discovered [GitHub Action's environment variables](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables), which provides a cool way to not checkout the `tests/data` submodule: checkout only `capa-rules`, which also automatically checkouts the correct version without needing to update the submodule after the checkout (as it uses `$GITHUB_SHA` environment variable).
The token I had removed in https://github.com/fireeye/capa-rules/pull/40. I thought it was needed because I didn't need it in the other action, but I have forgotten that this is …
=> Improve capa checkout in sync workflow

nursery/enumerate-processes-via-ntquerysysteminformation.yml, nursery/read-process-memory.yml
QueryWorkingSet from psapi will also work in a similar fashion to VirtualQueryEx.  
PoC code is on github for using QueryWorkingSet or VirtualQueryEx  -> https://github.com/SpiderLabs/malware-analysis/blob/master/C/queryWorkingSet.c 
A blog post with full instructions can be found here -> https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/new-memory-scraping-technique-in-cherry-picker-pos-malware/
Both calls will ultimately land at NtQueryVirtualMemory.
I'm not sure if there is a process to modify authors of these rules as contributors commit up changes, so I'm leaving the author field as is.
=> Adding QueryWorkingSet from psapi to be used in ReadProcessMemory rule and second NtQuerySystemInformation rule.

data-manipulation/checksum/luhn/luhn-credit-card-validation.yml, data-manipulation/checksum/luhn/validate-credit-card-number-with-luhn-algorithm.yml
Adding support for the Luhn credit card validation routine as seen in `1d8fd13c890060464019c0f07b928b1a`.  
This is also the variant that is used in the Dexter malware family.  I put luhn's in it's own folder, under checksums, due to there being a couple different common implementations out there.  As I work through more samples, I'll get the rules up for those variants.
An example of running this against the sample will show the following output.
```
luhn credit card validation
namespace  data-manipulation/checksum
author     @_re_fox
scope      function
examples   1d8fd13c890060464019c0f07b928b1a:0x401920, 60abaef3fda131ffa20df480cb3f8029:0x4048e0
function @ 0x4048E0
and:
basic block:
and:
number: 0x0 @ 0x4048E6, 0x404933
number: 0x2 @ 0x4048ED
number: 0x4 @ 0x4048F4
number: 0x6 @ …
```
=> Adding luhn credit card validation routine

doc/format.md
PR to enable descriptions for statement nodes (not merged yet): https://github.com/fireeye/capa/pull/209
=> doc: Document descriptions for statement nodes

collection/screenshot/capture-screenshot.yml
The logic to capture a screenshot in sample `7204e3efc2434012e13ca939db0d0b02` is slightly different than the capture screenshot rule currently in collection/screenshot/capture-screenshot.yml.
This is just a patch to the rule to cover the sample.  I'll upload the sample to the testfiles-repo
=> Updating screenshot capability to cover Arkei Stealer

nursery/add-file-to-cabinet-file.yml, nursery/flush-cabinet-file.yml, nursery/open-cabinet-file.yml
Adding new rules to detect manipulation of cabinet (`.cab`) files. Rules placed in nursery until example samples are found.
More information: https://docs.microsoft.com/en-us/windows/win32/msi/cabinet-files
=> new rules for cabinet file manipulation

doc/format.md
There is PR to remove the `characteristic(switch)` feature in capa: https://github.com/fireeye/capa/pull/232
=> Remove characteristic(switch) from the documentation

data-manipulation/encryption/camellia/encrypt-data-using-camellia.yml
Fixes #105 
Updates encrypt-data-using-camellia so that it works with 112f9f0e8d349858a80dd8c14190e620
I ran into some issues when getting these ready to submit - let me know if you'd like me to open tickets for any these:
When I run `capafmt.py` on these, it changes the bottom section to the following, which breaks the rule:
```
- and:
- string: /A09E667F3BCC908B/i
description: sigma1_str
- string: /B67AE8584CAA73B
description: sigma2_str
- string: /C6EF372FE94F82BE/i
description: sigma3_str
- string: /54FF53A5F1D36F1C/i
description: sigma4_str
- string: /10E527FADE682D1D/i
description: sigma5_str
- string: /B05688C2B3E6C1FD/i
description: sigma6_str
```
When testing this rule with capa's `-v` parameter, the reported offsets don't appear to be correct:
```
python2.7 ~/.local/bin/capa -r …
```
=> Fix #105 - Update encrypt-data-using-camellia

nursery/empty-recycle-bin-quiet.yml, nursery/empty-recycle-bin-quietly.yml
Expands on existing nursery rule https://github.com/fireeye/capa-rules/blob/master/nursery/empty-the-recycle-bin.yml
=> rule: empty recycle bin quiet

data-manipulation/checksum/crc32/hash-data-with-crc32.yml
A sample I looked at today uses the same immediate value as the existing capa rule. However, it is split across two 16-bit operations instead of a 32-bit immediate.
Updated rule and added sample hash.
=> Add 16-bit constants for CRC32

anti-analysis/packer/peshield/packed-with-peshield.yml, anti-analysis/packer/petite/packed-with-petite.yml, anti-analysis/packer/rlpack/packed-with-rlpack.yml, anti-analysis/packer/upack/packed-with-upack.yml, anti-analysis/packer/y0da/packed-with-y0da-crypter.yml
Handful of packer rules based on section names or strings.  
Submitting for cursory detection, the rules could be made more resilient with function features.  All supporting files are in https://github.com/fireeye/capa-testfiles/pull/25
=> Initial set of packer rules

nursery/reference-114dns-dns-server.yml, nursery/reference-alidns-dns-server.yml, nursery/reference-cloudflare-dns-server.yml, nursery/reference-comodo-secure-dns-server.yml, nursery/reference-google-public-dns-server.yml, nursery/reference-hurricane-electric-dns-server.yml, nursery/reference-kornet-dns-server.yml, nursery/reference-l3-dns-server.yml, nursery/reference-opendns-dns-server.yml, nursery/reference-quad9-dns-server.yml, nursery/reference-verisign-dns-server.yml
initially wanted to describe behavior of this TIGERPLUG dropper here: https://www.virustotal.com/gui/file/784ceff596d94ef365ae261ae43a83c43d52e04dc46b09a8fb5960772bca4a00/content/strings
but the DNS servers are not referenced directly by the dropper, and i haven't gotten around to extracting the payloads.
=> add rules describing hardcoded DNS servers

.github/workflows/tests.yml
Ensure that rules and most recent release are compatible.
Broken after enabling new `- description` entries, reported in https://github.com/fireeye/capa/issues/339.
Works with `- description` entries removed, see https://github.com/fireeye/capa-rules/actions/runs/315925603.
Plan to reenable descriptions and merge after new capa release.
=> CI: Run rules with latest release

nursery/resolve-function-by-hash.yml
adds most common lib/export hashes for ROR13. in theory would could add rules for each of the algos described in the blog post, though im concerned there would be hundreds of thousands of new rule statements that would slow things down.
https://www.fireeye.com/blog/threat-research/2012/11/precalculated-string-hashes-reverse-engineering-shellcode.html
=> add resolve-function-by-hash

host-interaction/log/winevt/access/access-the-windows-event-log.yml
Graduating nursery rule into namespace folder, and updated with example.
=> Graduate rule nursery/access-the-windows-event-log.yml

host-interaction/process/inject/inject-apc.yml
Another rule graduation, I added in an additional optional constant for `THREAD_ALL_ACCESS` 
As observed in https://github.com/LordNoteworthy/al-khaser/blob/136de8393de69dd9cab8103316e6da32681200df/al-khaser/CodeInjection/QueueUserAPC.cpp#L135
=> Graduate inject-apc.yml

anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml, anti-analysis/anti-disasm/contain-anti-disasm-techniques.yml, collection/credit-card/parse-credit-card-information.yml, data-manipulation/checksum/adler32/compute-adler32-checksum.yml, data-manipulation/hashing/fnv/hash-data-using-fnv.yml, executable/subfile/pe/contain-an-embedded-pe-file.yml, host-interaction/file-system/read/read-virtual-disk.yml, host-interaction/file-system/windows-file-protection/bypass-windows-file-protection.yml, host-interaction/hardware/keyboard/simulate-ctrl-alt-del.yml, host-interaction/registry/delete/delete-registry-value.yml, lib/calculate-modulo-256-via-x86-assembly.yml, lib/create-or-open-file.yml, lib/delay-execution.yml, lib/peb-access.yml, lib/validate-payment-card-number-using-luhn-algorithm-with-lookup-table.yml, lib/validate-payment-card-number-using-luhn-algorithm-with-no-lookup-table.yml, linking/static/cryptopp/linked-against-crypto.yml, linking/static/openssl/linked-against-openssl.yml, linking/static/polarssl/linked-against-polarsslmbed-tls.yml, linking/static/zlib/linked-against-zlib.yml
Added MBC mappings to lib and linking namespaces, as well as for rules in other namespaces that were added after those namespaces were originally mapped to MBC. Where possible, all but nursery namespace have been mapped.
=> update mappings for mbc (part 5)

executable/resource/extract-resource-via-kernel32-functions.yml, host-interaction/file-system/files/list/enumerate-files-via-ntdll-functions.yml, host-interaction/file-system/write/write-file.yml, host-interaction/os/info/get-system-information.yml, host-interaction/process/inject/inject-apc.yml, host-interaction/process/list/enumerate-processes-via-ntquerysysteminformation.yml, lib/allocate-memory.yml, lib/open-process.yml, lib/open-thread.yml, load-code/pe/access-pe-header.yml
removing the `ntdll` requirement from function features that are exported by both `ntdll` and `ntoskrnl` will improve hits for kernel drivers e.g. #240.
=> removing ntdll requirement from function features exported by both ntdll and ntoskrnl

nursery/inspect-load-icon-resource.yml
interesting anti-analysis technique most likely meant to evade sandbox/emulation.
from MS docs for `LoadIcon`: _To use one of the predefined icons, set the hInstance parameter to NULL and the lpIconName parameter to one of the following values.....If the function fails, the return value is NULL._
observed numerous calls to `LoadIcon` passing `NULL` for first argument and random identifier for second argument, with a check for `NULL` return following each call.
=> adding inspect-load-icon-resource.yml

nursery/capture-screenshot-go.yml, nursery/enumerate-processes-go.yml, nursery/golibrary-for-registry.yml, nursery/golibrary-for-wmi.yml, nursery/includes-static-assets.yml
Add rules for capabilities in Go files based on used third-party libraries. Since Go files are not dynamically linked, imports can not be used. Instead, the functionality has to be inferred from strings found in the file. All rules requires that the "compiled with Go" rule first has matched. The following capabilities have been added:
WMI functionality:
Detects if the file has been compiled with StackExchange's WMI library.
Screenshot capability:
Looks for lazy loading of specific Windows dlls + the name of functions that needs to be resolved.
Included static assets:
Go have multiple third-party libraries to embeds assets. The rule looks for the presence of the most common used libraries.
Process enumeration:
Process enumeration via a third-party library.
Windows registry interaction: …
=> New capabilities for Go files

lib/validate-payment-card-number-using-luhn-algorithm-with-no-lookup-table.yml
Updated to trigger on a variant of the Luhn checksum used in a TinyPOS sample of `3679ae3462d5005a1967f278b1c40f39`. 
Rather than using an `add` or `shl` for multiplying by 2, this version explicitly uses a `imul`.  In the final step `mod 10`, the authors use a `div`, rather than an `idiv/cdq` or an optimized `shr/imul` combination. 
I checked against the `capa-testfiles` repo and the rule doesn't introduce any false negatives.  This version of the rule is less restrictive (doesn't have a `not: characteristic: nzxor`) so there may be a slight risk of false positives, but I haven't seen any yet.
=> Update Luhn's algorithm to catch TinyPOS implementation

data-manipulation/hashing/fnv/hash-data-using-fnv.yml
observed `64-bit` sample referencing `32-bit` number constants:
```asm
mov     ecx, 811C9DC5h
lea     rdx, [rax+rbx]
jmp     short loc_2002EED9
movzx   eax, byte ptr [rbx]
imul    ecx, 1000193h
xor     ecx, eax
add     rbx, 1
```
removing arch requirement from number constants to up the matches.
=> hash-data-using-fnv: removing arch requirement from number constants

nursery/encrypt-data-using-curve25519.yml
Tested the rule against a couple of known samples that implement Curve25519 encryption. Unfortunately this kind of encryption is not based on well-known constants apart from the setting of the initial buffer.
So, in a nutshell - we'd need to detect a buffer being initialized as follows:
buf[0x00] = 0xf8
buf[0x20] = buf[0x20] & 0x3f | 0x40
This looks unique enough to not produce false positives but I'll strengthen it further if it does.
Let me know if you have any questions and/or feedback. It's my first rule so I'm eager to learn how to do this properly. :)
=> Adding an initial rule for detecting Curve25519 algorithms

.github/workflows/tests.yml
Capa master doesn't support Python 2 anymore. Update the `test.yml` workflow to use Python 3 to run the rule linter.
=> ci: run tests with Python3

.github/workflows/sync.yml
Update new rules in capa repository's CHANGELOG with a GitHub Action automatically with every push (for example merge of PR).
You can see how the created commit looks like here: https://github.com/Ana06/capa/commit/7d7def34548434051af318197e736f815c7658c0
And the action running here: https://github.com/Ana06/capa-rules/runs/2528333012?check_suite_focus=true
Needs https://github.com/fireeye/capa/pull/549 to be merged to work.
Related: https://github.com/fireeye/capa/issues/457.
=> ci: Update CHANGELOG automatically

.github/scripts/changelog_author.py, .github/workflows/sync.yml
The sync GH action only works for a single author, producing unexpected results when using list of authors.
This change also prevent problems with new files that are not rules (`.yml`). (such as `.github/scripts/changelog_author.py`)
Closes https://github.com/fireeye/capa/issues/555
=> ci: support multiple author in sync GH

executable/installer/inno-setup/packaged-as-an-inno-setup-installer.yml
Add `packaged-as-an-inno-setup-installer` which looks for simple strings associated with Inno Setup installers.  These strings appear to be present in installers produced using at least Inno Setup version 3 through the latest (Inno Setup version 6).
Related: https://github.com/fireeye/capa-testfiles/pull/95
=> Add packaged-as-an-inno-setup-installer

data-manipulation/hashing/djb2/hash-data-using-djb2.yml
The djb2 hash function was recently observed being used by Gamaredon for Windows API function hashing, so this PR
adds `hash-data-using-djb2` to look for a commonly referenced djb2 implementation
Related: https://github.com/fireeye/capa-testfiles/pull/93
=> Add hash-data-using-djb2

doc/format.md, internal/limitation/file/README.md, internal/limitation/file/internal-autoit-file-limitation.yml, internal/limitation/file/internal-dotnet-file-limitation.yml, internal/limitation/file/internal-installer-file-limitation.yml, internal/limitation/file/internal-packer-file-limitation.yml
https://github.com/fireeye/capa/pull/591
=> file limitation rules

.github/workflows/sync.yml
The GH action which updates the number of rules in the CHANGELOG counted files that are not `.yml`.
From https://github.com/fireeye/capa/commit/8f1ce68e96619e22ea406ee4cee3595426102c31#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed: `82 - 77 = 4` 🤯
=> ci: fix rule counting in CHANGELOG

anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml, data-manipulation/encryption/hc-128/encrypt-data-using-hc-128.yml, data-manipulation/encryption/sosemanuk/encrypt-data-using-sosemanuk.yml, executable/installer/iexpress/packaged-as-an-iexpress-self-extracting-archive.yml, executable/installer/inno-setup/packaged-as-an-inno-setup-installer.yml, host-interaction/network/domain/enumerate-domain-computers-via-LDAP.yml, host-interaction/network/domain/enumerate-domain-computers-via-ldap.yml, host-interaction/network/domain/get-domain-controller-name.yml, host-interaction/network/domain/get-domain-information.yml, host-interaction/session/get-logon-sessions.yml
Adds `get-domain-controller-name` and `enumerate-domain-computers-via-LDAP`, and also has some metadata updates related to rules I wrote previously
See https://github.com/fireeye/capa-testfiles/pull/98 for test files
=> Add get-domain-controller-name and enumerate-domain-computers-via-LDAP

collection/credit-card/parse-credit-card-information.yml
I have come across a sample that compare with all ASCII characters, which triggers this rule (although the sample doesn't parse credit card information). Ensure that there is not a comparison with `m`, `n`, `o` and `p` (as they are in the middle of the alphabet and not part of the hex char set) to avoid this case.
=> tighten up parse credit card rule

doc/format.md
per #390
> ok, it was new to me, that the regular strings in capa don't do a substring search. just came from doing lots of YARA and there it's default unless you use "fullword" ;)
> 
> maybe write that explicit in the documentation, just found it here for regex, but no that's the other way around for normal strings:
> 
> ```
> Regexes should be surrounded with / characters. By default, capa uses case-sensitive matching and assumes leading and trailing wildcards. 
> ```
> 
> from https://github.com/fireeye/capa-rules/blob/master/doc/format.md
=> clarify verbatim string matching

linking/static/openssl/linked-against-openssl.yml
=> adding additional detection strings to linked-against-openssl.yml

data-manipulation/compression/decompress-data-using-aplib.yml
Remove `count(characteristic(calls from)): 2 or more` to detect aPLib compression used in BlackMatter v3.0.
Also the linting fails with B43FCA5283BFC7022553EFF663683834 cause capa throws UnsupportedFormatError, so I removed it from the rule. Lmk if you guys want me to add it back.
=> Small fix for aPLib detection

nursery/create-registry-key-via-stdregprov.yml, nursery/delete-registry-key-via-stdregprov.yml, nursery/delete-registry-value-via-stdregprov.yml, nursery/query-or-enumerate-registry-key-via-stdregprov.yml, nursery/query-or-enumerate-registry-value-via-stdregprov.yml, nursery/set-registry-value-via-stdregprov.yml
see #470 for more information. essentially, we hit on the strings passed to `GetObject`, e.g. `StdRegProv`, and `GetMethod`, e.g. `CreateKey`.
=> adding registry manipulation via StdRegProv

data-manipulation/compression/decompress-data-using-ucl.yml
This PR adds a new rule that detects multiple nrv2\* decompression functions present in the UCL library.
=> Add decompress-data-using-ucl.yml

linking/static/wolfcrypt/linked-against-wolfcrypt.yml, linking/static/wolfssl/linked-against-wolfssl.yml
This PR adds two new rules that match on strings found in binaries statically linked with wolfSSL or wolfCrypt.
wolfCrypt is a backend library used by wolfSSL but it can also be used separately.
=> Add linked-against-wolfssl.yml and linked-against-wolfcrypt.yml

anti-analysis/packer/pespin/packed-with-pespin.yml
This PR adds a new rule that matches on PE section names created by PESpin/PESpin x64 packers.
=> Adding packed-with-pespin.yml

communication/http/client/download-url.yml, communication/receive-data.yml
renaming and adding new APIs to `download-url-to-file.yml`. closes #496.
=> updating download-url-to-file.yml

collection/get-current-user-on-linux.yml, communication/socket/tcp/send/obtain-transmitpackets-callback-function-via-wsaioctl.yml, host-interaction/bootloader/manipulate-boot-configuration.yml, host-interaction/file-system/change-file-permission-on-linux.yml, host-interaction/log/clfs/read-data-from-clfs-log-container.yml, host-interaction/recycle-bin/empty-recycle-bin-quietly.yml, load-code/shellcode/execute-shellcode-via-enumuilanguages.yml, load-code/shellcode/execute-shellcode-via-windows-fibers.yml, load-code/shellcode/spawn-thread-to-rwx-shellcode.yml
Looked at capa rules and found a few newer rules without MBC/ATT&CK mappings. Please consider these suggested mappings.
=> update mappings for mbc (part 7)

anti-analysis/anti-forensic/spoof-parent-pid.yml
Added example and attack mapping to spoof-parent-pid.yml. Moved to anti-analysis/anti-forensic from nursery.
=> Updated and graduated spoof-parent-pid.yml

anti-analysis/anti-av/protect-spawned-processes-with-mitigation-policies.yml
New rule that identifies use of UpdateProcThreadAttribute to enable "BlockDLLs" and Arbitrary Code Guard mitigation policies on spawned processes
=> Adding protect-spawned-processes-with-mitigation-policies.yml

anti-analysis/anti-av/block-operations-on-executable-memory-pages-using-arbitrary-code-guard.yml
New rule that identifies use of SetProcessMitigationPolicy to set dynamic code policy (Arbitrary Code Guard) of the process to prevent it from creating and modifying code pages in memory - possibly preventing injection of EDR DLLs.
=> Adding block-operations-on-executable-memory-pages-using-arbitrary-code-guard.yml

anti-analysis/anti-av/block-operations-on-executable-memory-pages-using-arbitrary-code-guard.yml, anti-analysis/anti-av/protect-spawned-processes-with-mitigation-policies.yml, anti-analysis/anti-debugging/debugger-detection/check-processdebugport.yml, anti-analysis/anti-vm/vm-detection/check-for-microsoft-office-emulation.yml, anti-analysis/packer/gopacker/packed-with-gopacker.yml, anti-analysis/reference-analysis-tools-strings.yml, host-interaction/process/dump/create-process-memory-minidump.yml, host-interaction/service/run-as-service.yml, impact/inhibit-system-recovery/delete-volume-shadow-copies.yml, load-code/pe/rebuild-import-table.yml, nursery/check-for-process-debug-object.yml, nursery/check-processdebugflags.yml, nursery/check-systemkerneldebuggerinformation.yml, nursery/check-thread-yield-allowed.yml
This PR fixes MBC names and IDs in the continuity of #524.
In my second commit, I've made names/IDs changes that could have more impacts and which are only based on my thoughts. Some MBC categories are not present anymore and sometime a method could be associated to the behavior. 
Here are the rules I am talking about if you want to discuss the changes: 
| Capa rule  | MBC |
| ------------- | ------------- |
| Rule “protect spawned processes with mitigation policies” | Defense Evasion::Disable or Evade Security Tools::Modify Policy [F0004.005] |
| Rule “block operations on executable memory pages using Arbitrary Code Guard” | Defense Evasion::Disable or Evade Security Tools::Modify Policy [F0004.005]
| Rule “check for process debug object” | Anti-Behavioral Analysis::Debugger …
=> Fix MBC names and IDs

host-interaction/process/inject/hijack-thread-execution.yml
make `- match: allocate RWX memory` optional
=> update hijack-thread-execution.yml to match additional scenarios

compiler/v/compiled-with-v.yml, compiler/zig/compiled-with-zig.yml
New rules that identify executables compiled with V(lang) and Zig(lang).
=> Adding compiled-with-v.yml and compiled-with-zig.yml

anti-analysis/anti-forensic/spoof-parent-pid.yml, communication/socket/tcp/send/obtain-transmitpackets-callback-function-via-wsaioctl.yml, data-manipulation/encryption/hc-128/encrypt-data-using-hc-128-via-wolfssl.yml, doc/format.md, nursery/add-file-to-cabinet-file.yml, nursery/create-registry-key-via-stdregprov.yml, nursery/create-restart-manager-session.yml, nursery/delete-registry-key-via-stdregprov.yml, nursery/delete-registry-value-via-stdregprov.yml, nursery/encrypt-data-using-fakem-cipher.yml, nursery/flush-cabinet-file.yml, nursery/get-storage-device-properties.yml, nursery/open-cabinet-file.yml, nursery/prompt-user-for-credentials.yml, nursery/query-or-enumerate-registry-key-via-stdregprov.yml, nursery/query-or-enumerate-registry-value-via-stdregprov.yml, nursery/set-registry-value-via-stdregprov.yml
Several rules use a string value to define a reference. This can cause issues in calling code as the value may be a list or a string. Checking the defined format states that this field lists related information, so I believe this should always be a list of references. 
Updated format.md to define the field as a list of related info.  
Updated these rules to define the reference value as a list entry.
=> Update rules to use a list item instead of a string value for reference

nursery/load-dotnet-assembly.yml
Adding a new rule that detects when a sample loads a .NET assembly.
=> Add load-dotnet-assembly.yml

host-interaction/software/get-installed-programs.yml
Graduate @mr-tz's rule  `get-installed-programs.yml`.  I added in additional (optional) string from the sample that is referenced in the example.
=> Graduate get-installed-programs.yml

persistence/authentication-process/act-as-credential-manager-dll.yml, persistence/authentication-process/act-as-password-filter-dll.yml
Adding two new rules for DLLs designed to act as Windows password filter or credential manager
=> Add act-as-credential-manager-dll.yml and act-as-password-filter-dll.yml

host-interaction/uac/bypass/bypass-uac-via-token-manipulation.yml
Update rule based on analysis of a sample from the wild. This sample has not been added to `examples` because it needs to be unpacked manually from memory.
The APIs have been broken into three categories:
- APIs used to run an elevated program.
- APIs for obtaining token information.
- APIs for using the token.
I removed `GetStartupInfoW`, which is not essential to the UAC bypass technique and is typically used to run the elevated process in a hidden window.
Only the string `wusa.exe` is currently included. Opened issue #615 to discuss whether this should be expanded.
=> Improve UAC bypass rule based on sample in the wild

host-interaction/uac/bypass/bypass-uac-via-rpc.yml
Quick rule to detect UAC bypass using RPC.
One query on the inclusion of the byte version of the GUID. This does appear in the reference sample (at 0x140020EC0) and is referenced in the function that we expect test cases to hit. However, the reference is not direct because the code references a `MIDL_STUB_DESC` structure (at 0x140020D60) which then references the bytes in an `RpcInterfaceInformation` structure.
Advice on how to handle this appreciated - would it be worth moving the bytes to `file` scope?
=> Add initial UAC bypass with RPC rule

nursery/get-windows-directory-from-kuser_shared_data.yml, nursery/get-windows-directory-kuser-shared-data.yml
This structure is at a fixed offset in both 32 and 64 bit Windows. This rule looks for a typical function call setup to copy data from this location.
It may be possible to instead look for only the known memory address, which would catch samples that manually access memory rather than calling a function. However, this would be more prone to false positives where the same constants are used for other reasons.
=> Rule for accessing Windows directory from KUSER_SHARED_DATA

nursery/encrypt-data-using-openssl-dsa.yml, nursery/encrypt-data-using-openssl-ecdsa.yml, nursery/encrypt-data-using-openssl-rsa.yml
Use Serialized OIDs to identify RSA, DSA and ECDSA from OpenSSL.
Reference:
- https://github.com/openssl/openssl/blob/fdc5043d58900663b493147298e64f11353b35fe/crypto/objects/obj_dat.h
Identifying the bytes `2A 86 48 86 F7 0D 01 01 01` was key to identify the encryption in a Rust sample I have recently analysed. Next time capa will speed me up. 😄 I can not share the sample, so adding these rules to the nursery.
=> Use Serialized OIDs to identify OpenSSL

.github/scripts/create_releases.py, .github/workflows/release.yml
supports #642 
In https://github.com/mandiant/capa/blob/master/.github/workflows/tag.yml we create a rules tag for every new code release.
This workflow then creates a respective release.
See this in Action in my fork:
- https://github.com/mr-tz/capa-rules/actions/runs/3749612283/jobs/6368283950
- result: https://github.com/mr-tz/capa-rules/releases/tag/v4.1.0
I find it pretty handy that we can just use the default ZIP and TGZ archives in the Assets section.
=> add release workflow

runtime/dotnet/dotnet-hook-module.yml, runtime/dotnet/execute-via-dotnet-startup-hook.yml
closes #646
example file:
https://github.com/mandiant/capa-testfiles/pull/149
=> add "execute via .NET startup hook"

.github/workflows/tests.yml
from https://github.com/mandiant/capa-rules/pull/647
=> tests: better detect rule name

data-manipulation/hashing/djb2/hash-data-using-djb2.yml, nursery/resolve-function-by-djb2-hash.yml
This PR improves the detection for usage of the djb2 hashing algorithm by adding the multiplication of the hash by 33 part of the instructions into the existing rule, as well as adding a new rule that detects the general usage of such hashing algorithm for function resolving.
=> Improve djb2 detection

data-manipulation/encryption/elliptic-curve/encrypt-data-using-curve25519.yml
- Added description that documents targeted code
- Added description for each instruction
- Added an additional number often used to clear only bit 7 of the last byte of the secret key
=> Update encrypt-data-using-curve25519 rule

data-manipulation/encryption/rc4/encrypt-data-using-rc4-prga.yml
closes #435
Library ID fails and RC4 PRGA matches on `___strgtold12_l`. An upped BB count prevents this.
Are there concerns on the upper limit value here?
=> add upper limit for basic block count

nursery/hash-data-using-whirlpool.yml
ref #632 
viv doesn't identify the example function, unfortunately, due to it being referenced via a chain of two pointers.
=> add whirlpool hash

host-interaction/registry/create/set-registry-value.yml
Part of #679 
This PR improves the detection of the `reg.exe add` command. Some samples split the command up into multiple parts. For example, a sample might pass `reg.exe` as one argument and `ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\ ...` as another.
=> Split the 'reg.exe add' check into multiple strings

data-manipulation/compression/compress-data-via-zlib-inflate-or-deflate.yml
This rule passes the thorough linting test and closes #497
=> Rule for zlib inflate/deflate

communication/http/reference-http-user-agent-string.yml, doc/format.md
=> add HTTP User-Agent rule

anti-analysis/anti-debugging/debugger-detection/check-for-debugger-via-api.yml, host-interaction/process/list/enumerate-processes-via-ntquerysysteminformation.yml, nursery/check-for-process-debug-object.yml, nursery/check-systemkerneldebuggerinformation.yml
=> improve debug detection features

anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-device.yml, anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-dns-suffix.yml, anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-genuine-state.yml, anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-process-name.yml, anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-registry.yml, doc/format.md, host-interaction/file-system/files/list/enumerate-files-on-windows.yml, host-interaction/file-system/files/list/enumerate-files-recursively.yml, nursery/check-for-windows-sandbox-via-mutex.yml, nursery/get-os-version-in-dotnet.yml
- Updates documentation to include `property` and .NET constructor features (closes #722)
- Fixes capitalization of some rules
- Adds new API to detect OS read in .NET
=> update rule documentation and improve .NET detection for OS gather

anti-analysis/anti-debugging/destroy-software-breakpoint-capability.yml, nursery/destroy-software-breakpoint-capability.yml
`VirtualProtectEx(CurProc, &DbgBreakPoint, 1, PAGE_RWX, &oldProtect);`
`DbgBreakPoint[0] = <some new value here, usually NOP or RET>`
=> adding new rule for destroying capability of adding software breakpoints

nursery/contain-a-thread-local-storage-tls-section-in-dotnet.yml
This rule aims to detect .NET files containing a `TLS` section (see #725). A quick VT hunt using `tag:assembly section:tls` matched less than 10 samples so it appears the presence of a `TLS` section in .NET files is pretty uncommon. The referenced blog demonstrates how a `TLS` section can be injected into a `.NET` file to execute potentially malicious code so IMO it's worth noting this to capa users.
=> add new rule to detect .NET files w/ uncommon TLS section

data-manipulation/encryption/aes/encrypt-data-using-aes-mixcolumns-step.yml
=> AES MixColumns detection

load-code/pe/enumerate-pe-sections.yml
part of #296
`./Chapter_01L/Lab01-01.exe:0x401000`
=> loosen locality of features

nursery/hash-data-using-sha512managed-in-dotnet.yml
Adds rule for detecting hashing using .NET's Sha512Managed class
=> Add rule hash-data-using-sha512managed-in-dotnet.yml

host-interaction/process/inject/inject-apc.yml
E1055.004 cannot be validated at the moment
=> revert missing MBC tag so linter succeeds again

host-interaction/service/query-service-configuration.yml
=> query service configuration

linking/runtime-linking/resolve-function-by-brute-ratel-badger-hash.yml
Add resolve-function-by-brute-ratel-badger-hash.yml
=> Add resolve-function-by-brute-ratel-badger-hash.yml

nursery/enumerate-browser-history.yml, nursery/hash-data-using-crc32b.yml, nursery/hash-data-using-sha1-via-x86-extensions.yml, nursery/hash-data-using-sha256-via-x86-extensions.yml, nursery/inspect-load-icon-resource.yml, nursery/manipulate-unmanaged-memory-in-dotnet.yml, nursery/mixed-mode.yml, nursery/save-image-in-dotnet.yml, nursery/search-for-credit-card-data.yml, nursery/set-http-user-agent-in-dotnet.yml, nursery/set-web-proxy-in-dotnet.yml, nursery/terminate-process-by-name.yml
This PR adds the `dynamic: scope` to some remaining rules that are missing it.
=> Add remaining dynamic-syntax rules missing the  dynamic scope

anti-analysis/anti-vm/vm-detection/check-for-foreground-window-switch.yml, anti-analysis/anti-vm/vm-detection/detect-vm-via-disk-hardware-wmi-queries.yml, anti-analysis/anti-vm/vm-detection/detect-vm-via-motherboard-hardware-wmi-queries.yml, host-interaction/file-system/create-virtual-file-system-in-dotnet.yml, host-interaction/memory/create-new-application-domain-in-dotnet.yml, linking/runtime-linking/resolve-function-by-brute-ratel-badger-hash.yml
=> Update Mappings for MBC (part 11)

nursery/send-sms-on-android.yml
First rule for Android (native code called via JNI), here from a private 64-bit .so file. Very similar code is also referenced in https://stackoverflow.com/questions/30175062/jni-callvoidmethod-leads-to-fatal-signal-6-and-invalid-indirect-reference.
Question: do we want to mix mobile with desktop for namespaces and ATT&CK?
=> add `send SMS on Android`

nursery/encrypt-data-using-rc4-via-systemfunction032.yml
Added Advapi32.SystemFunction032 capa rule.
Kind regards,
Richard
=> encrypt data using RC4 via SystemFunction032

malware-family/plugx/match-known-plugx-module.yml
=> PLUGX: make more restrictive to fix FP

communication/socket/tcp/create-tcp-socket.yml, nursery/access-camera-in-dotnet-on-android.yml, nursery/capture-microphone-audio-in-dotnet-on-android.yml, nursery/capture-screenshot-in-dotnet-on-android.yml, nursery/check-for-incoming-call-in-dotnet-on-android.yml, nursery/check-for-outgoing-call-in-dotnet-on-android.yml, nursery/compiled-with-xamarin.yml, nursery/get-os-version-in-dotnet-on-android.yml, nursery/get-system-information-in-dotnet-on-android.yml
Adding new rules based on #706 . This PR may be impacted by the discussions in #818 regarding mobile ATT&CK techniques. I wanted to open a PR for discussion before diving too far into creating new rules.
Questions:
- Should Android example files be placed in separate tests folder?
=> init add of Xamarin rules

anti-analysis/anti-vm/vm-detection/check-for-windows-sandbox-via-genuine-state.yml, communication/socket/create-vmci-socket.yml, host-interaction/file-system/read/read-file-via-mapping.yml
fixes for #855
when generating subscope rules (in the format of rule/uuid) we emit subrules at all scopes, when matching in static flavor this includes dynamic subscopes which can never be matched if static and dynamic are both required, so e.g. `file-system/read/read-file-via-mapping.yml` before this update could not match.
https://github.com/mandiant/capa/blob/51ddadbc87b113dda18495b49e490f8452292b87/capa/rules/__init__.py#L925-L928
@yelhamer is this intended behavior or a bug? I think our current documentation calls this out differently (and I assumed it works differently since I created these faulty rules in the first place 😄 )
=> fix logic after dynamic update

lib/allocate-memory.yml, lib/allocate-or-change-rw-memory.yml, lib/change-memory-protection.yml
As mentioned by @mike-hunhoff , the rule in its current format can match if the `number: 0x4 = PAGE_READWRITE` feature is present in another call in the same thread. Setting the rule's dynamic scope to `call` helps prevent this.
=> Fix the dynamic flavor scope for allocate-or-change-rw-memory.yml

README.md
This PR replaces an old example rule in the documentation that still used the `scope` field, with a more appropriate one that showcases dynamic capa rules and is updated to the correct format.
=> Update README to showcase dynamic rules

collection/network/capture-public-ip.yml
This PR adds additional domains associated with WAN IP capturing in `collection/network/capture-public-ip.yml`, primarily ones typically found in Chinese malware.
=> Add additional domains for known IP obtaining services

collection/network/capture-public-ip.yml
Sample contains IP string at the mentioned address but not a function that references it. This rule focuses on the function/thread scope not the file level.
=> Fix linter fail

.github/workflows/sync.yml, README.md
This does not rely on `img.shields.io`, simplifies the workflow code, and remove the need for the noisy commits in capa-rules. We still need the commits in capa to sync the submodule. I'll send a PR in capa to use the new badge in a moment.
This requires giving the token gist persmissions, which I have already done. So it should work when we merge it.
We are using gist badges in [VM-Packages](https://github.com/mandiant/VM-Packages) since a few days, in case you want to see it working. We update the number of packages when adding a new package and the the daily package failures once a day.
=> [CI] Use badge in gist for rules number in README

.github/workflows/release.yml, .github/workflows/sync.yml, .github/workflows/tests.yml
Update all actions using a deprecated version of Node: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20
=> [CI] Update GitHub actions to versions using Node 20

nursery/encrypt-data-using-salsa20-or-chacha.yml
=> fix encrypt-data-using-salsa20-or-chacha.yml

communication/dns/resolve-dns.yml, communication/socket/create-raw-socket.yml, communication/socket/get-socket-status.yml, communication/socket/initialize-winsock-library.yml, communication/socket/receive/receive-data-on-socket.yml, communication/socket/send/send-data-on-socket.yml, communication/socket/set-socket-configuration.yml, communication/socket/tcp/connect-tcp-socket.yml, communication/socket/tcp/create-tcp-socket.yml, communication/socket/udp/send/create-udp-socket.yml, nursery/get-socket-information.yml
Programs can import networking routines from ws2_32 by ordinal, and this is occasionally seen in the while, such as in PMA 01-01.dll.
This file shows an example of mapping ordinals to names for ws2_32: https://github.com/phracker/HopperScripts/blob/9468cdadb2c139d474662ae82716a5098e7350e4/WS2_32.dll%20Ordinals%20to%20Names.py#L8
Today, we rely on vivisect (or the binary analysis backend) to resolve ordinal numbers to human-readable names; however, not all analysis backends may have this mapping. So, we can extend our rules to also match these ordinals.
For example, with these changes using a backend that doesn't support ordinal mapping:
=> add API features for ws2_32 ordinals

host-interaction/file-system/files/list/enumerate-files-on-linux.yml, host-interaction/file-system/files/list/enumerate-files-recursively.yml, host-interaction/file-system/read/read-file-on-linux.yml, host-interaction/file-system/write/write-file-on-linux.yml, host-interaction/hardware/memory/get-memory-information.yml, host-interaction/mutex/create-semaphore-on-linux.yml, host-interaction/mutex/lock-file.yml, host-interaction/mutex/lock-semaphore-on-linux.yml, host-interaction/mutex/unlock-semaphore-on-linux.yml, host-interaction/process/create/create-process-on-linux.yml, host-interaction/session/get-current-user-on-linux.yml, host-interaction/thread/create/create-thread.yml, lib/delay-execution.yml, lib/duplicate-stdin-and-stdout.yml, linking/runtime-linking/link-many-functions-at-runtime.yml, nursery/get-current-pid-on-linux.yml, nursery/get-password-database-entry-on-linux.yml, nursery/link-function-at-runtime-on-linux.yml, nursery/set-thread-name-on-linux.yml
I first started to create (copy/paste) new rules `... on Android` but that duplicates a lot and Android is based on the Linux kernel so I think the names are fine (but happy to discuss).
=> add android OS where applicable

compiler/go/compiled-with-go.yml
`go1.` would for example match on `logo1.jpg`
=> reduce FPs by adjusting `go1.` substring feature

data-manipulation/encryption/dpapi/encrypt-data-using-dpapi.yml
Update encrypt-data-using-dpapi.yml rule - add `RtlEncryptMemory`/`SystemFunction040` and `RtlDecryptMemory`/`SystemFunction041`.
`CryptProtectMemory` and `CryptUnprotectMemory` are wrappers for `SystemFunction040` and `SystemFunction041` respectively.
=> Update encrypt-data-using-dpapi.yml rule

collection/keylog/log-keystrokes-via-application-hook.yml, host-interaction/gui/set-application-hook.yml, linking/runtime-linking/link-function-at-runtime-on-windows.yml
ref: https://github.com/mandiant/capa/issues/2124
=> fix the scope of some rules with dependencies

anti-analysis/anti-av/overwrite-dll-text-section-to-remove-hooks.yml, anti-analysis/anti-av/unhook-a-dll.yml
=> Add rule unhook-a-dll.yml

host-interaction/log/debug/write-event/print-debug-messages.yml, lib/calculate-modulo-256-via-x86-assembly.yml, nursery/delete-file-on-linux.yml
=> update linux/android rules and reduce fps for intel-specific rules

linking/static/sqlite3/linked-against-sqlcipher.yml
https://github.com/mandiant/capa-testfiles/pull/257
=> add linked against SQLCipher

host-interaction/network/traffic/filter/delete-network-filter-via-wfp-api.yml, host-interaction/network/traffic/filter/enumerate-network-filters-via-wfp-api.yml
Add two new CAPA rules:
host-interaction/network/traffic/filter/delete-network-filter-via-wfp-api.yml
host-interaction/network/traffic/filter/enumerate-network-filters-via-wfp-api.yml
=> Add delete-network-filter-via-wfp-api.yml and enumerate-network-filters-via-wfp-api.yml

data-manipulation/encryption/hc-128/encrypt-data-using-hc-128-via-wolfssl.yml
Tested on a Winnti malware sample as the screenshot attached.
=> Update HC-128 (variation used in Winnti malware)

nursery/access-unmanaged-com-objects-in-dotnet.yml, nursery/implement-ui-automation-client-in-dotnet.yml, nursery/interact-with-shortcut-via-iwshshortcut-in-dotnet.yml, nursery/interact-with-windows-scripting-host-in-dotnet.yml, nursery/use-dotnet-library-simplejson.yml, nursery/use-dotnet-library-websocket-sharp.yml
=> rules: dotnet: adding new .NET rules

host-interaction/os/hide-shutdown-actions-via-policy.yml
This PR adds a rule that detects registry values related to hiding shutdown actions (i.e., logout, shutdown, reboot, etc.), specifically ones using policy registry values. This is often abused by ransomware to prevent mid-encryption-shutdowns.
=> Add rule for detecting hiding shutdown actions

host-interaction/process/get-process-filename.yml
Testfile PR: https://github.com/mandiant/capa-testfiles/pull/262
=> Add rule get-process-filename.yml

.github/scripts/create_releases.py, .github/workflows/release.yml, .github/workflows/sync.yml, .github/workflows/tests.yml
ref: https://github.com/mandiant/capa/pull/2467
=> update analogous to capa repo, removing Python 3.8

nursery/get-password-database-entry-on-linux.yml, nursery/get-shadow-password-file-entry-on-linux.yml, nursery/set-shadow-password-file-entry-on-linux.yml
added detections for reading/writing shadow file, password database
=> added detections for reading/writing shadow file, password database

collection/browser/get-chrome-cookiemonster.yml, collection/browser/get-chrome-elevation-service.yml, collection/browser/get-elevation-service-for-chromium-based-browsers.yml, collection/get-steam-token.yml
This PR adds three new rules spotted amongst various types of infostealers/dumping tools (Stealc, Vidar, ChromeKatz),
1. `collection/browser/get-chrome-cookiemonster.yml`
- Detects strings related to locating processes related to Chromium's [CookieMonster class](https://www.chromium.org/developers/design-documents/network-stack/cookiemonster/)
- Typically used by infostealers or memory dumpers to extract Cookies directly from Chromium-based browsers
2. `collection/browser/get-chrome-elevation-service.yml`
- Detects IID and CLSIDs for Chrome ElevationService of various editions
- Typically used by infostealers via RPC to decrypt App-bound Encryption-related data
3. `collection/get-steam-token.yml`
- Detects references to known Steam tokens
- Typically used by Vidar and its relevant …
=> Add rules for various stealer techniques

host-interaction/file-system/copy/copy-file.yml, host-interaction/file-system/move/move-file.yml, host-interaction/file-system/write/write-file-on-windows.yml, host-interaction/registry/create/set-registry-value.yml
To reduce false positives, we change the dynamic scope of a couple of operations to `call`.
E.g., writing to the registry is always done in one Windows API call, so we change the scope from `thread` to `call`.
Original discussion: https://github.com/mandiant/capa-rules/discussions/951
=> Change dynamic scope to call for atomic operations

linking/static/touchsocket/linked-against-touchsocket.yml, runtime/dotnet/compiled-with-dotnet-aot.yml
This PR adds a new rule for detecting .NET binaries that are compiled Ahead-of-Time (AoT), as well as another rule for detecting strings related to the TouchSocket library, a Chinese-developed networking library that has been adopted by at least one Chinese APT group. 
Additional discussion is required surrounding the example linked in the rule, as both of the rules feature a sample that is a known malicious sample that exceeds 15MB in size and can cause a significant amount of time to process, and may cause timeout for the CI pipeline. I can replace this with a self-written sample Hello World that would meet the requirements for both of these rules and be significantly smaller (~1.6MB) and faster, if other maintainers believe this would be a better approach.
=> Add .NET AoT & TouchSocket linking detection 

host-interaction/process/create/create-process-suspended.yml
> With the Debug Injection method, the ransomware first uses the function “CreateProcessW” with the “DEBUG_ONLY_THIS_PROCESS” creation flag. Creating the “Explorer.exe” process in this state allows the ransomware to suspend the process and modify its memory. This is when then ransomware calls “NtMapViewOfSection” to copy itself to the process and fix its relocations. Afterward, it calls “NtGetContextThread” to receive the thread context of the main thread for “Explorer.exe”. It then sets the instruction pointer (EIP) to the mapped ransomware’s selected entry point. “ContinueDebugEvent” is then called to continue the execution of “Explorer.exe” and the following call is to “DebugActiveProcessStop” which finally detaches the ransomware’s debugger from the process.
_source: …
=> update create-process-suspended to include DEBUG_ONLY_THIS_PROCESS

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/false_negative.md, .github/ISSUE_TEMPLATE/false_positive.md, .github/ISSUE_TEMPLATE/rule_idea.md
- Change the Code of Conduct by Google's default Code of Conduct in the ISSUE TEMPLATES, as the used linked has been removed from capa in https://github.com/mandiant/capa/pull/2556 for consistency with other Google projects.
- Add CONTRIBUTING file with information about CLA and Google's code of conduct to follow Google conventions/policies. Include also other details to make contributing easier. We can add more details in the future to this file too.
=> Add CONTRIBUTING file & update ISSUE TEMPLATES

anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings-targeting-virtualbox.yml, anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings-targeting-vmware.yml, anti-analysis/anti-vm/vm-detection/reference-anti-vm-strings-targeting-xen.yml, communication/socket/tcp/create-tcp-socket-via-raw-afd-driver.yml, nursery/send-data-to-internet.yml, persistence/office/act-as-office-com-add-in.yml
removing duplicate features found in following rules using new lint (https://github.com/mandiant/capa/pull/257):
- act as Office COM add-in
- create TCP socket via raw AFD driver
- reference anti-VM strings targeting VMWare
- reference anti-VM strings targeting VirtualBox
- reference anti-VM strings targeting Xen
- send data to Internet
=> remove duplicate features from some rules

anti-analysis/anti-forensic/self-deletion/self-delete.yml
Removes FP regex match `/del\s*\S/` for `api-ms-win-appmodel-runtime-l1-1-2` discovered during testing.
Input:
```
del /path/to/file
del "/path/to/file"
api-ms-win-appmodel-runtime-l1-1-2
cmd.exe /c "ping 127.0.0.1 & del \"/path/to/file\""
cmd.exe /c "ping 127.0.0.1&del \"/path/to/file\""
```
Matches:
```
del /path/to/file
del "/path/to/file"
& del \"/path/to/file\""
&del \"/path/to/file\""
```
=> reduce fps for self-delete.yml

internal/limitation/dynamic/internal-dotnet-file-limitation.yml
ref https://github.com/mandiant/capa/issues/2591
=> internal-dotnet-file-limitation.yml: make it valid for static scope too

host-interaction/process/terminate/terminate-process.yml
Fixes https://github.com/mandiant/capa-rules/issues/970
[x] No CHANGELOG update needed
[x] No new tests needed
[x] No documentation update needed
=> extend terminate-process.yml to include exit_group #970

persistence/registry/run/persist-via-run-registry-key.yml
I'm seeing quite a few FPs because of the previous `string(/Run/i)` feature, e.g., the sandbox run for a sample I'm looking at contains many references to `Bruno` in various file paths, which are triggering this rule to match. I've opted to be explicit about the registry key matches to reduce FPs.
=> tighten "persist via run registry key" to reduce FPs

communication/socket/connect-socket.yml, communication/socket/tcp/connect-tcp-socket.yml, communication/socket/udp/connect-udp-socket.yml
- Add a generic `connect socket` rule capturing common connection APIs.
- Refactor the TCP connect rule to require a match on `create TCP socket` and the  `connect socket` rule
- Add a new UDP connect rule that requires a match on `create UDP socket` and the  `connect socket` rule.
Closes #965.
=> Addresses #965: Create separate rules for socket connects (TCP/UDP)

anti-analysis/anti-forensic/clear-logs/clear-windows-event-logs-remotely.yml
EvtOpenLog has been removed from the logic since it is unnecessary for EvtClearLog. The only handle EvtClearLog can accept is a session handle (acquired by EvtOpenSession), which is optional and only needed for remote operations.
=> Fix 'clear Windows event logs remotely'

communication/socket/tcp/create-tcp-socket.yml, communication/socket/udp/send/create-udp-socket.yml, nursery/create-udp-socket.yml
Fixes https://github.com/mandiant/capa-rules/issues/964
I have also added number: 17 = IPPROTO_UDP , can make the rule more precise by explicitly matching cases where the UDP protocol is specified. (but not needed specifically)
[x] No CHANGELOG update needed
[x] No new tests needed
[x] No documentation update needed
=> improve TCP/UDP socket creation matching #964

host-interaction/process/inject/allocate-or-change-rwx-memory.yml
I'm seeing many FPs for dynamic runs when matching constant `0x40` using _span of calls_ scope. This reduces dynamic scope to _call_ and splits matching across static (_basic block_ scope) and dynamic (_call_ scope).
=> remove FPs from allocate-or-change-rwx-memory.yml

host-interaction/mutex/check-mutex-on-windows.yml, host-interaction/mutex/create-or-open-mutex-on-windows.yml
Adding APIs observed in CAPE reports. I'm not sure how CAPE logs dynamically resolved APIs, e.g., in this sample I'm observing that CAPE logs undocumented _Nt*_ counterparts for dynamically resolved APIs, e.g. _NtCreateMutant_ is logged for _CreateMutexA_...
=> add APIs to mutex-related rules on Windows to reduce FNs

host-interaction/driver/unload-driver.yml, host-interaction/filter/unload-minifilter-driver.yml
Sysmon driver can be unloaded using `FilterUnload` from `fltlib.dll`.
Proof of concept:
https://github.com/getel-arch/Unload-Sysmon/blob/main/src/main.c
=> Unload minifilter drivers

anti-analysis/anti-forensic/unload-sysmon.yml
Capability of unloading minifilter driver + reference to `SysmonDrv` in the file.
I'm not sure what is the correct place for this, `anti-analysis/anti-av` or `anti-analysis/anti-forensic`?
=> Unload Sysmon

host-interaction/network/address/get-local-ipv4-addresses.yml
Use `call` subscope to avoid erroneous API matches.
=> tighten subscope for get-local-ipv4-addresses
